services:
  # MongoDB服务
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db

  # Milvus向量数据库服务
  milvus-standalone:
    image: milvusdb/milvus:v2.3.3
    container_name: milvus-standalone
    env_file: .env
    environment:
      ETCD_CFG.auto-compaction-mode: revision
      ETCD_CFG.auto-compaction-retention: "1000"
      COMMON_CFG.releaseVersion: 2.3.3
    volumes:
      - ./data/milvus:/var/lib/milvus
    ports:
      - "${MILVUS_PORT}:19530"
      - "9091:9091"
    restart: always

volumes:
  mongodb_data:
  milvus_data: